version: '3.9'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  data_driver:
    build: ./data_driver
    environment:
      - DATABASE_URL=sqlite:///./vulnerabilities.db
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - data_volume:/app
    depends_on:
      - rabbitmq

  fastapi:
    build: ./fastapi_app
    environment:
      - DATA_DRIVER_URL=http://data_driver:8000
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - data_driver

  api_gateway:
    build: ./api_gateway
    ports:
      - "80:80"
    depends_on:
      - fastapi

volumes:
  data_volume:
