FROM python:3.11-slim

WORKDIR /data_driver

COPY ./data_driver /data_driver

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
